title: mikepetridisz Blog
description: My Personal Blog
author: Miklos Petridisz
github: https://github.com/mikepetridisz
about: I do Big Data Engineering
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/mikepetridisz"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/miklos-petridisz/"
    - icon: fa-github
      link: "https://github.com/mikepetridisz"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://mikepetridisz.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
